### PR TITLE
Made a single error message not stall the repo finding process

### PR DESCRIPTION
**Pull request by nonnominandus**
Love the idea of this project. But on my machine it crashed on a single repo, so I refactored it so that it continues processing after encountering a erroneous repo. With this changes it works perfectly on my machine, it shows the error and picks up all other repos. It also picks up the repo that gave rise to the error in some way which I do not really understand but will look into.

The git changes look a bit all over the place, but essentially I moved the code after `match open_repo` into the match statement in the function `find_repos`.

I see you do not have any contributing guidelines or license in the repo but I assume you appreciate PRs and I allow my changes to be integrated in the code and licensed under any open source license.

### CODE REVIEW

**Comment by nonnominandus** [comment]
Update: the repo that gave rise to the issue indeed was broken. And it did not pick it up anyways it did pick up another repo with a very similar name.
So the current state of the code (without this PR) works. It is up to you if you want a fail early or fail late system.

**Comment by hakoerber** [comment]
Hello!

Very cool, thank you for the contribution! I think having the `find` command report an error and continuing is preferable to failing completely, so this is nice.

> I see you do not have any contributing guidelines

Yes, I just opened #12 to remedy this. License is GPLv3 (see [here](https://github.com/hakoerber/git-repo-manager/blob/793d07f39fd0e570cbffb8f2c850d0255c8cbbe8/Cargo.toml#L27), I just added the license as `LICENSE` as well).

If you don't mind, I'd add you to a `CONTRIBUTOR` file (with name and email). Is that ok for you?

**Comment by nonnominandus** [comment]
Great, I am okay with being added to the contributor file.

**Comment by hakoerber** [comment]
[Done](https://github.com/hakoerber/git-repo-manager/commit/9afc062e7c300ccda248c5e97acd0cd9151f6a3d)!

If you have any further ideas for improvements, let me know!

**Comment by hakoerber** [comment]
See https://github.com/hakoerber/git-repo-manager/blob/c66620a0fcd277db097b8d40222bcaec9fb33a3f/e2e_tests/test_repos_find.py#L162 for an e2e test to prevent regressions.

**Pull request merged**
